# server:
#   port: 8080
#   white-label:
#     enabled: true
#   error:
#     include-message: always
#     include-binding-errors: always
#     include-stacktrace: never
#     include-exception: true

# management:
#   endpoint:
#     health:
#       probes:
#         enabled: true
#   endpoints:
#     web:
#       exposure:
#         include:
#           - prometheus
#           - health
#           - info

# springdoc:
#   api-docs:
#     enabled: true

# springfox:
#   documentation:
#     swagger-ui:
#       enabled: true

logging:
  level:
    root: info
    # Maze
    tech.maze: info
    # this entry disables the tomcat logging exception stack traces as we already control the logging in ResponseHandler
    org.apache.catalina.core.ContainerBase: off
    # HTTP request/response logging
    si.mazi.rescu: warn
    # database
    org.hibernate.SQL: warn
    com.zaxxer.hikari.HikariConfig: warn
    com.zaxxer.hikari: warn
    # caching
    org.springframework.cache: warn
    com.github.benmanes.caffeine: warn
    io.lettuce: warn
    # AWS Cloud
    io.awspring.cloud.sqs: info
    software.amazon: info

spring:
  main:
    banner-mode: 'off'
  datasource:
    enabled: true
    default:
      configuration:
        maximum-pool-size: 2
        minimum-idle: 2 # INFO: minimum number of idle connections maintained by HikariCP in a connection pool
        max-lifetime: 1800000 # INFO: maximum lifetime in milliseconds of a connection in the pool after it is closed.
        idle-timeout: 30000
        connection-timeout: 20000 # INFO: maximum number of milliseconds that a client will wait for a connection
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
  cache:
    enabled: false
